### ISSUE TITLE
joker

### ISSUE THREAD

**Issue by borkdude** [robpike/lisp#7]
This is a Clojure (Lisp) interpreter implemented in go:

https://github.com/candid82/joker

Closing this issue, it's just for your information.

**Comment by robpike** [comment]
Thanks for the information. Looks interesting.

**Comment by divs1210** [comment]
There's also [sabre](https://github.com/spy16/sabre), a lisp engine written in Go, for implementing lisps. Also Clojure inspired.

**Comment by borkdude** [comment]
@robpike Also check out a work in progress project:

https://github.com/nooga/let-go

> This is supposed to be a compiler and bytecode VM for a language resembling Clojure as close as possible.
